# Generated by Django 2.0.9 on 2018-11-14 03:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_name', models.CharField(blank=True, default='NULL', max_length=50)),
                ('mobile_number', models.CharField(blank=True, default='NULL', max_length=8)),
                ('incident_time', models.DateTimeField(default=datetime.datetime(2018, 11, 14, 3, 8, 33, 390026, tzinfo=utc))),
                ('incident_location', models.CharField(blank=True, default='NULL', max_length=100)),
                ('incident_department', models.CharField(default='NULL', max_length=100)),
                ('incident_region', models.CharField(choices=[('North West', 'North West'), ('Central Singapore', 'Central Singapore'), ('South East', 'South East'), ('North East', 'North East')], default='NULL', max_length=100)),
                ('incident_category', models.CharField(default='NULL', max_length=100)),
                ('incident_type', models.CharField(default='NULL', max_length=100)),
                ('incident_status', models.CharField(choices=[('New', 'New'), ('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='New', max_length=100)),
                ('incident_description', models.CharField(blank=True, default='NULL', max_length=200)),
            ],
        ),
    ]
