# Generated by Django 2.0.9 on 2018-11-13 02:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_name', models.CharField(blank=True, default='NULL', max_length=50)),
                ('mobile_number', models.CharField(blank=True, default='NULL', max_length=8)),
                ('incident_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('incident_location', models.CharField(blank=True, default='NULL', max_length=100)),
                ('incident_department', models.CharField(default='NULL', max_length=100)),
                ('incident_region', models.CharField(default='NULL', max_length=100)),
                ('incident_category', models.CharField(default='NULL', max_length=100)),
                ('incident_type', models.CharField(default='NULL', max_length=100)),
                ('incident_status', models.CharField(choices=[('New', 'New'), ('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='NEW', max_length=100)),
                ('incident_description', models.CharField(blank=True, default='NULL', max_length=200)),
            ],
        ),
    ]
