# Generated by Django 2.1.1 on 2018-10-04 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcentre', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Incident',
        ),
    ]
