# Generated by Django 2.1.1 on 2018-10-16 13:34

from django.db import migrations, models
import utilities.incidentstatus
import utilities.incidenttype
import utilities.region


class Migration(migrations.Migration):

    dependencies = [
        ('callcentre', '0004_auto_20181016_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='caller_name',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_region',
            field=models.CharField(choices=[(utilities.region.Region('South West'), 'South West'), (utilities.region.Region('North West'), 'North West'), (utilities.region.Region('Central Singapore'), 'Central Singapore'), (utilities.region.Region('South East'), 'South East'), (utilities.region.Region('North East'), 'North East')], default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='mobile_number',
            field=models.CharField(default='NULL', max_length=8),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_category',
            field=models.CharField(choices=[(utilities.incidenttype.IncidentType('Emergency Ambulance'), 'Emergency Ambulance'), (utilities.incidenttype.IncidentType('Rescue & Evacuation'), 'Rescue & Evacuation'), (utilities.incidenttype.IncidentType('Fire Fighting'), 'Fire Fighting'), (utilities.incidenttype.IncidentType('Gas Leak Control'), 'Gas Leak Control')], default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_description',
            field=models.CharField(default='NULL', max_length=400),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_location',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_status',
            field=models.CharField(choices=[(utilities.incidentstatus.IncidentStatus('New'), 'New'), (utilities.incidentstatus.IncidentStatus('Planned'), 'Planned'), (utilities.incidentstatus.IncidentStatus('In Progress'), 'In Progress'), (utilities.incidentstatus.IncidentStatus('Resolved'), 'Resolved')], default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_time',
            field=models.DateTimeField(),
        ),
    ]
