# Generated by Django 2.1.1 on 2018-10-16 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('callcentre', '0005_auto_20181016_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
