# Generated by Django 2.0.9 on 2018-10-17 11:29

from django.db import migrations, models
import utilities.incidentstatus


class Migration(migrations.Migration):

    dependencies = [
        ('callcentre', '0006_auto_20181016_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='incident_department',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='incident_description',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='incident_region',
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_status',
            field=models.CharField(choices=[(utilities.incidentstatus.IncidentStatus('New'), 'New'), (utilities.incidentstatus.IncidentStatus('Planned'), 'Planned'), (utilities.incidentstatus.IncidentStatus('In Progress'), 'In Progress'), (utilities.incidentstatus.IncidentStatus('Resolved'), 'Resolved')], default='NEW', max_length=100),
        ),
    ]
