# Generated by Django 2.0.9 on 2018-10-18 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcentre', '0007_auto_20181017_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='incident_category',
        ),
    ]
