# Generated by Django 2.0.9 on 2018-10-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcentre', '0009_auto_20181022_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('--------Emergency Situations--------', '--------Emergency Situations--------'), ('----Natural Hazards----', '----Natural Hazards----'), ('Fire', 'Fire'), ('Haze', 'Haze'), ('Tsunami', 'Tsunami'), ('Typhoon', 'Typhoon'), ('Earthquake', 'Earthquake'), ('Earthquake Aftershocks', 'Earthquake Aftershocks'), ('----Epidemic----', '----Epidemic----'), ('Dengue', 'Dengue'), ('HIV/AIDS', 'HIV/AIDS'), ('Bird-flu', 'Bird-flu'), ('Zika', 'Zika'), ('----Traffic Accidents----', '----Traffic Accidents----'), ('Single Car Accidents', 'Single Car Accidents'), ('Two Car Collisions', 'Two Car Collisions'), ('Multiple Vehicle Pile-up', 'Multiple Vehicle Pile-up'), ('----Incidents within Crowded Areas----', '----Incidents within Crowded Areas----'), ('Terrorist Attacks', 'Terrorist Attacks'), ('Mass Shooting', 'Mass Shooting'), ('Other Useful Information', 'Other Useful Information'), ('Weather', 'Weather'), ('Civil Defense Shelters', 'Civil Defense Shelters')], default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_category',
            field=models.CharField(choices=[('Emergency Ambulance', 'Emergency Ambulance'), ('Rescue & Evacuation', 'Rescue & Evacuation'), ('Fire Fighting', 'Fire Fighting'), ('Gas Leak Control', 'Gas Leak Control')], default='NULL', max_length=100),
        ),
    ]
