# Generated by Django 2.0.9 on 2018-11-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcentre', '0010_auto_20181022_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_status',
            field=models.CharField(choices=[('New', 'New'), ('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='NEW', max_length=100),
        ),
    ]
