# Generated by Django 2.1.1 on 2018-10-18 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20181018_1159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
