# Generated by Django 2.1.1 on 2018-10-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=100)),
            ],
        ),
    ]
