# Generated by Django 2.1.1 on 2018-10-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test',
            new_name='category',
        ),
        migrations.AddField(
            model_name='test',
            name='place',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
